site_name: MasterMind
repo_url: https://github.com/martel-innovate/MasterMind
site_description: MasterMind Documentation
docs_dir: 'docs'
theme: readthedocs
pages:
    - Home: 'index.md'
    - User Manual:
        - 'Introduction': 'user/introduction.md'
        - 'Quick Start': 'user/quickstart.md'
        - 'Step by Step guide': 'user/stepByStep.md'
        - 'MasterMind Data Models': 'user/dataModels.md'
        - 'API v1': 'user/apiv1.md'
    - Installation & Administration Manual:
        - 'Introduction': 'admin/introduction.md'
        - 'Installation': 'admin/installation.md'
        - 'Service Catalog': 'admin/catalog.md'
        - 'Actor Management': 'admin/actor_management.md'
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
